// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrationen brauchen eine Session-/Direktverbindung. Die Anwendung kann
    // weiterhin den Supavisor Transaction Pooler aus DATABASE_URL verwenden.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
